### PR TITLE
Add socks proxy and various fixes

### PR DESCRIPTION
**Pull request by kortov**
- add socks proxy
- add proxy type radiobutton selector
- bump bot dependency to the latest 4.5.0
- rename plugin name to telegram-plugin-notifier
- remove tests (they test the bot not plugin and fail anyway when proxy is needed)

### CODE REVIEW

**Comment by kortov** [comment]
@ItgLvb Hi, you don't mind if I send you PR's and you review/merge them ? Because you have the latest fork, others don't maintain their repos. If you're not interested in it, I'll try to maintain my fork instead (I think there is much to improve in the project)

**Comment by ItgLvb** [comment]
Why not. I am actively using this project. And I plan to improve it.

**Comment by kortov** [comment]
Glad to hear that, I have some ideas I’ll try to write them via issues/PRs

**Comment by kortov** [comment]
@ItgLvb can you open issues tab, please? Settings -> issues
image
image

**Pull request merged**
